version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/react-app

hooks:


  AfterInstall:
    - location: scripts/build_react.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 60
      runas: root
